version: '3'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: dockerfile
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: yankewei
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: yankewei
    container_name: mysql

networks:
  database:
    external: true